const API="https://kztechsite.onrender.com";const T=sessionStorage.getItem("adm")||localStorage.getItem("kz_admin_session");if(T)sessionStorage.setItem("adm",T);
const E=id=>document.getElementById(id);const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function api(path,opt={}){const h=new Headers(opt.headers||{});h.set("Authorization","Bearer "+T);if(opt.body&&!h.has("Content-Type"))h.set("Content-Type","application/json");const r=await fetch(API+path,{...opt,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Erro de comunicação");return d}
let pages=[],files=[],current=null;
const typeInfo={HTML:["HTML","Estrutura da página"],CSS:["CSS","Estilos e responsividade"],JS:["JS","Lógica e componentes"],CMS:["CMS","Regras de conteúdo"],BACKEND:["BACKEND","API e servidor"],DATA:["DADOS","Catálogo central de preços"]};
function pageFromUrl(){return new URLSearchParams(location.search).get("page")||"home"}
async function init(){if(!T){E("status").textContent="Sessão ausente.";return}try{const x=await api("/api/admin/cms/pages");pages=x.pages||[];E("pageSelect").innerHTML=pages.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+" · "+esc(p.route)+"</option>").join("");E("pageSelect").value=pages.some(p=>p.id===pageFromUrl())?pageFromUrl():"home";await loadPage(E("pageSelect").value)}catch(e){E("status").textContent=e.message}}
async function loadPage(page){E("pageTitle").textContent=(pages.find(p=>p.id===page)||{}).name||"Página";E("status").textContent="Carregando fontes…";try{const x=await api("/api/admin/cms/files?page="+encodeURIComponent(page));files=x.files||[];renderFiles();const first=files.find(f=>f.type!=="REACT")||files[0];if(first)await openFile(first.path);E("status").textContent="Fontes carregadas"}catch(e){E("status").textContent=e.message}}
function renderFiles(){E("fileList").innerHTML=files.map(f=>{const ti=typeInfo[f.type]||[f.type,""];return '<button class="cms-file '+(current?.path===f.path?"active":"")+'" data-path="'+esc(f.path)+'"><span class="cms-type">'+esc(ti[0])+'</span><b>'+esc(ti[1])+'</b><small>'+esc(f.path)+'</small></button>'}).join("")+'<div class="cms-file cms-react"><span class="cms-type">REACT</span><b>React</b><small>Não utilizado no site atual</small></div>';document.querySelectorAll(".cms-file[data-path]").forEach(b=>b.onclick=()=>openFile(b.dataset.path))}
async function openFile(path){try{E("code").disabled=true;E("editorNotice").textContent="Lendo "+path+"…";const x=await api("/api/admin/cms/file?path="+encodeURIComponent(path));current={...x};E("fileName").textContent=typeInfo[files.find(f=>f.path===path)?.type]?.[0]||"Fonte";E("filePath").textContent=path;E("code").value=x.content;E("code").disabled=false;E("editorMeta").textContent=(x.size||x.content.length).toLocaleString("pt-BR")+" caracteres · branch "+x.branch;E("saveMeta").textContent="SHA: "+x.sha;E("editorNotice").textContent="Editando diretamente a fonte do repositório.";renderFiles()}catch(e){E("editorNotice").textContent=e.message;E("code").value="";E("code").disabled=true}}
async function save(){if(!current)return;const b=E("save");b.disabled=true;b.textContent="Salvando…";try{const x=await api("/api/admin/cms/file",{method:"PUT",body:JSON.stringify({path:current.path,content:E("code").value,sha:current.sha,message:"CMS: atualizar "+current.path})});current.sha=x.sha||current.sha;E("saveMeta").textContent="Salvo · commit "+(x.commit||"—");E("editorNotice").textContent="Alteração salva diretamente no GitHub.";b.textContent="✓ Salvo";setTimeout(()=>b.textContent="Salvar na fonte",1500)}catch(e){E("editorNotice").textContent=e.message;b.textContent="Salvar na fonte"}finally{b.disabled=false}}
E("pageSelect").onchange=()=>{history.replaceState(null,"","cms.html?page="+encodeURIComponent(E("pageSelect").value));loadPage(E("pageSelect").value)};E("reload").onclick=()=>current&&openFile(current.path);E("save").onclick=save;E("out").onclick=()=>{sessionStorage.removeItem("adm");localStorage.removeItem("kz_admin_session");location.href="./"};init();